#GITHUB ACTIONS

name: CI/CD for sqior services

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: ghcr.io/sqior/sqior-api
  VERSION: v3.0.1  # You can automate this from git tags or SHA

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code (Repo 1)
      - name: Checkout Service Repo
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and Push Docker Image
      - name: Build and Push Image
        run: |
          docker build -t $IMAGE_NAME:$VERSION ./services/sqior-api
          docker push $IMAGE_NAME:$VERSION

      # OPTIONAL: Trivy Image Scan
      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: $IMAGE_NAME:$VERSION
          scan-type: 'image'
          severity: 'CRITICAL,HIGH'

      # Update config in Repo 2 (customer config repo)
      - name: Update Config Repo for Target Customers
        run: |
          CUSTOMERS=("hospital_berlin" "hospital_munich")  # You can automate this from YAML or DB
          for customer in "${CUSTOMERS[@]}"; do
            git clone https://x-access-token:${{ secrets.CUSTOMER_REPO_PAT }}@github.com/sqior/config-$customer.git
            cd config-$customer/overlays/$customer/

            # Update deployment.yaml with new image tag
            yq e '.spec.template.spec.containers[0].image = "'"$IMAGE_NAME:$VERSION"'"' -i deployment.yaml

            git config user.name "sqior-ci-bot"
            git config user.email "ci@sqior.com"
            git add deployment.yaml
            git commit -m "Update image to $VERSION"
            git push origin main

            cd ../../..
          done

